# Generated by Django 3.2.7 on 2021-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
