# Generated by Django 3.2.7 on 2021-09-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_alter_updates_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='content',
            field=models.TextField(default='None Content'),
        ),
    ]
