# Generated by Django 3.2.7 on 2021-09-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_alter_updates_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='content',
            field=models.TextField(),
        ),
    ]
